name: Node.js CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20.10.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        # with:
        #   node-version: "14"

      - name: Install dependencies
        run: cd frontend/ && npm install
        # run: cd ../backend/ && npm install

      # - name: Run tests
      #   run: npm test

      - name: Deploy on Cloud
        run: |
          case "${{ github.ref }}" in
            refs/heads/main)
              DEPLOY_URL="https://prod.example.com"
              ;;
            refs/heads/staging)
              DEPLOY_URL="https://staging.example.com"
              ;;
            refs/heads/cicd-setup))
              curl "https://api.render.com/deploy/srv-cncrme6g1b2c739ji2tg?key=iSipfFr9sFY" && curl "https://api.render.com/deploy/srv-cncs0mun7f5s73biedvg?key=_GLTDTTT_ss"
              ;;
          esac
          echo "Deployed..."
          # curl "Deploying to $DEPLOY_URL_BACKEND"
          # curl "Deploying to $DEPLOY_URL_FRONTEND"
          # Add deployment commands here
